name = "A2K-VANILLA-SERVER"
author = "A2KLAB"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49a2f9db194e75e33b3f18528d190ca432996821290ad567906f76cb9fa955d3"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.x", "1.21.3", "1.21.4"]
