name = "A2K-VANILLA-SERVER"
author = "A2KLAB"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e06a9b7f7d98c866604f5ad0a89c4f41f680d482dc40f5018e92ea147cd0be6"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
